### ISSUE TITLE
indexedDb data store

### ISSUE THREAD

**Issue by gregglind** [mozilla/testpilot2#19]
this replaces sqlite.

tpstore : sqlite -> indexedDb

spec:
- async
- if writes fail we can forget them
- retrieve(data,objectgroup)
- delete study data
- get study data
- delete data from all studies

test up to 1000 writes per minute.

**Comment by gregglind** [comment]
@clarkbw , this is on you :)  It seems like I can't assign you to it... I will get you added on this project... maybe you aren't on moz?

**Comment by clarkbw** [comment]
I should be in the Mozilla group but I don't think I'm in the testpilot2 contributors yet.

**Comment by gregglind** [comment]
This is done in micropilot.  Will reuse.
